<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobPortal.Domain\JobPortal.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Auth\" />
    <Folder Include="DTOs\Candidate\" />
    <Folder Include="DTOs\Employer\" />
    <Folder Include="DTOs\Company\" />
    <Folder Include="DTOs\Job\" />
    <Folder Include="DTOs\Application\" />
    <Folder Include="DTOs\Interview\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Common\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
